# Generated by Django 2.1.2 on 2019-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20181112_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=100)),
                ('adult_count', models.IntegerField()),
                ('child_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
